# Basic Operation on Image


## Software And Packages Installation

In [25]:
import numpy as np
from matplotlib import pyplot as plt
from copy import deepcopy

In [26]:
import cv2

## Importing drawing & display

In [27]:
img = cv2.imread("watch.jpg", cv2.IMREAD_UNCHANGED)  # taking Picture unchanged

In [28]:
cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imwrite("watch1.png", img)

error: OpenCV(4.6.0) /io/opencv/modules/highgui/src/window.cpp:1267: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'


In [ ]:
img1 = cv2.imread("watch.jpg", cv2.IMREAD_GRAYSCALE)  # taking picture in grayscale

In [ ]:
cv2.imshow("image", img1)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imwrite("watchgray.png", img1)

In [ ]:
plt.imshow(img, cmap="gray", interpolation="bicubic")
plt.plot([50, 100], [80, 100], "c", linewidth=5)
plt.show()

In [ ]:
# Drawing

In [ ]:
cv2.line(img, (0, 0), (150, 150), (255, 255, 25), 15)  # Draw a line

NameError: name 'cv2' is not defined

In [ ]:
cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
cv2.rectangle(img, (15, 25), (200, 150), (0, 255, 0), 5)  # Draw a rectangle

array([[[255, 255,  25],
        [255, 255,  25],
        [255, 255,  25],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255,  25],
        [255, 255,  25],
        [255, 255,  25],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255,  25],
        [255, 255,  25],
        [255, 255,  25],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [ ]:
cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
cv2.circle(img, (100, 63), 55, (0, 0, 255), -1)  # Draw a circle

array([[[255, 255,  25],
        [255, 255,  25],
        [255, 255,  25],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255,  25],
        [255, 255,  25],
        [255, 255,  25],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255,  25],
        [255, 255,  25],
        [255, 255,  25],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [ ]:
cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
pts = np.array([[10, 5], [20, 30], [70, 20], [50, 10]], np.int32)
# pts = pts.reshape(-1,1,2)
cv2.polylines(img, [pts], True, (0, 255, 255), 3)  # Draw a polylines

array([[[255, 255,  25],
        [255, 255,  25],
        [255, 255,  25],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255,  25],
        [255, 255,  25],
        [255, 255,  25],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255,  25],
        [255, 255,  25],
        [255, 255,  25],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [ ]:
cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
font = cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(
    img, "Bijoy", (0, 130), font, 5, (255, 255, 25), 5, cv2.LINE_AA
)  # Draw a letter

array([[[255, 255,  25],
        [255, 255,  25],
        [255, 255,  25],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255,  25],
        [255, 255,  25],
        [255, 255,  25],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255,  25],
        [255, 255,  25],
        [255, 255,  25],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [ ]:
cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
img = cv2.imread("watch.jpg", cv2.IMREAD_COLOR)
img[55, 55] = [255, 252, 255]
px = img[55, 55]
print(px)

[255 252 255]


In [ ]:
# Region of Image
roi = img[100:150, 100:150]
print(roi)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [ ]:
img[100:150, 100:150] = [255, 255, 255]

watch_face = img[50:150, 150:250]
img[0:100, 0:100] = watch_face

cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
img = cv2.imread("watch.jpg", cv2.IMREAD_COLOR)

In [ ]:
def wind(image):
    cv2.namedWindow("image", cv2.WINDOW_NORMAL)
    cv2.imshow("image", image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [ ]:
wind(img)

In [ ]:
imgCol = cv2.imread("victoria.png", 1)

In [ ]:
wind(imgCol)

## Resizing, Croping, Exporting

In [ ]:
imgres = cv2.resize(imgCol, dsize=None, fx=0.2, fy=0.2, interpolation=cv2.INTER_CUBIC)

In [ ]:
cv2.imshow("window", imgres)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
crop = imgres[810:668, 800:670]

In [ ]:
cv2.imwrite("vm.png", imgres)

True